import type { Metadata } from "next";
import { Suspense } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SearchParamsProvider } from "./contexts/SearchParamsProvider";
import { ClientThemeProvider } from "./contexts/theme/ThemeProvider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen overflow-hidden`}
			>
				<Suspense fallback={<div className="theme-loading-fallback" />}>
					<ClientThemeProvider>
						<SearchParamsProvider>
							{children}
						</SearchParamsProvider>
					</ClientThemeProvider>
				</Suspense>
			</body>
		</html>
	);
}
